=== w0mby/LabyXML/CreateurLabyrinth/monde.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT monde (composant+)>
<!ATTLIST monde 
		longueur CDATA #IMPLIED
		largeur CDATA  #IMPLIED>
	<!ELEMENT composant (bloc+) >  
	<!ATTLIST composant 
		type CDATA #REQUIRED
		x CDATA #REQUIRED
		y CDATA #REQUIRED
		z CDATA #REQUIRED >
		<!ELEMENT bloc (rectangle+) >
		<!ATTLIST bloc
			x CDATA #REQUIRED
			y CDATA #REQUIRED
			z CDATA #REQUIRED>
			<!ELEMENT rectangle (vertex+,coordTex+)>
			<!ATTLIST rectangle
				mur (true|false) #REQUIRED
				sol (true|false) #REQUIRED
				tex CDATA #REQUIRED >
				<!ELEMENT vertex (#PCDATA) >
				<!ATTLIST vertex
					x CDATA #REQUIRED
					y CDATA #REQUIRED
					z CDATA #REQUIRED >
				<!ELEMENT coordTex (#PCDATA) >
				<!ATTLIST coordTex
					x CDATA #REQUIRED
					y CDATA #REQUIRED >

=== w0mby/LabyXML/CreateurLabyrinth/nouveau.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE monde SYSTEM "http://damas.hopto.org/monde.dtd">
<monde largeur="25" longueur="25">
<composant type="Carrefour" x="52.0" y="0.0" z="-16.0">
<bloc x="0.0" y="0.0" z="0.0">
<rectangle mur="false" sol="true" tex="sol.bmp">
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<vertex x="-2.0" y="-1.0" z="2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="false" sol="false" tex="plafond.bmp">
<vertex x="-2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="-2.0" y="2.0" z="2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
</bloc>
<bloc x="-4.0" y="0.0" z="0.0">
<rectangle mur="false" sol="true" tex="sol.bmp">
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<vertex x="-2.0" y="-1.0" z="2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="false" sol="false" tex="plafond.bmp">
<vertex x="-2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="-2.0" y="2.0" z="2.0"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="-2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="-2.0" y="2.0" z="2.0"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="-2.0" y="2.0" z="-2.0"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
</rectangle>
</bloc>
<bloc x="4.0" y="0.0" z="0.0">
<rectangle mur="false" sol="true" tex="sol.bmp">
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<vertex x="-2.0" y="-1.0" z="2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="false" sol="false" tex="plafond.bmp">
<vertex x="-2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="-2.0" y="2.0" z="2.0"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="-2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="-2.0" y="2.0" z="2.0"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="-2.0" y="2.0" z="-2.0"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
</rectangle>
</bloc>
<bloc x="0.0" y="0.0" z="-4.0">
<rectangle mur="false" sol="true" tex="sol.bmp">
<vertex x="-2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="false" sol="false" tex="plafond.bmp">
<vertex x="-2.0" y="2.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="-2.0" y="2.0" z="-2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="-2.0" y="2.0" z="2.0"/>
<vertex x="-2.0" y="2.0" z="-2.0"/>
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<vertex x="-2.0" y="-1.0" z="2.0"/>
<coordTex x="0" y="1"/>
<coordTex x="1" y="1"/>
<coordTex x="1" y="0"/>
<coordTex x="0" y="0"/>
</rectangle>
</bloc>
<bloc x="0.0" y="0.0" z="4.0">
<rectangle mur="false" sol="true" tex="sol.bmp">
<vertex x="-2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="false" sol="false" tex="plafond.bmp">
<vertex x="-2.0" y="2.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="-2.0" y="2.0" z="-2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="2.0" y="2.0" z="2.0"/>
<vertex x="2.0" y="2.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="-2.0"/>
<vertex x="2.0" y="-1.0" z="2.0"/>
<coordTex x="1" y="1"/>
<coordTex x="0" y="1"/>
<coordTex x="0" y="0"/>
<coordTex x="1" y="0"/>
</rectangle>
<rectangle mur="true" sol="false" tex="mur.bmp">
<vertex x="-2.0" y="2.0" z="2.0"/>
<vertex x="-2.0" y="2.0" z="-2.0"/>
<vertex x="-2.0" y="-1.0" z="-2.0"/>
<vertex x="-2.0" y="-1.0" z="2.0"/>
<coordTex x="0" y="1"/>
<coordTex x="1" y="1"/>
<coordTex x="1" y="0"/>
<coordTex x="0" y="0"/>
</rectangle>
</bloc>
</composant>
</monde>
